//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiniLithoApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CINIDBEntities : DbContext
    {
        public CINIDBEntities()
            : base("name=CINIDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_alfserial> tbl_alfserial { get; set; }
        public virtual DbSet<tbl_customer> tbl_customer { get; set; }
        public virtual DbSet<tbl_officeuse> tbl_officeuse { get; set; }
        public virtual DbSet<tmp_billdet> tmp_billdet { get; set; }
        public virtual DbSet<Balance_List> Balance_List { get; set; }
        public virtual DbSet<tbl_logdetail> tbl_logdetail { get; set; }
        public virtual DbSet<tbl_billdetails> tbl_billdetails { get; set; }
        public virtual DbSet<tbl_totaldetails> tbl_totaldetails { get; set; }
        public virtual DbSet<tbl_newbill> tbl_newbill { get; set; }
        public virtual DbSet<tbl_expence> tbl_expence { get; set; }
        public virtual DbSet<tbl_purchase> tbl_purchase { get; set; }
        public virtual DbSet<tbl_Employee> tbl_Employee { get; set; }
        public virtual DbSet<tbl_Supplier> tbl_Supplier { get; set; }
    
        public virtual ObjectResult<BillPrint1_Result> BillPrint1(string billNo)
        {
            var billNoParameter = billNo != null ?
                new ObjectParameter("BillNo", billNo) :
                new ObjectParameter("BillNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BillPrint1_Result>("BillPrint1", billNoParameter);
        }
    
        public virtual ObjectResult<SearchBillNo_Result> SearchBillNo(string fromBillNo, string toBillNo)
        {
            var fromBillNoParameter = fromBillNo != null ?
                new ObjectParameter("FromBillNo", fromBillNo) :
                new ObjectParameter("FromBillNo", typeof(string));
    
            var toBillNoParameter = toBillNo != null ?
                new ObjectParameter("ToBillNo", toBillNo) :
                new ObjectParameter("ToBillNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchBillNo_Result>("SearchBillNo", fromBillNoParameter, toBillNoParameter);
        }
    
        public virtual ObjectResult<SearchDate_Result> SearchDate(string fromDate, string todate)
        {
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var todateParameter = todate != null ?
                new ObjectParameter("Todate", todate) :
                new ObjectParameter("Todate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchDate_Result>("SearchDate", fromDateParameter, todateParameter);
        }
    
        public virtual ObjectResult<SearchMonth_Result> SearchMonth(Nullable<int> month, Nullable<int> year)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchMonth_Result>("SearchMonth", monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<USP_SEL_Contacts_Result> USP_SEL_Contacts(string sortOrder, Nullable<int> pageNo, Nullable<int> pageSize)
        {
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_Contacts_Result>("USP_SEL_Contacts", sortOrderParameter, pageNoParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<SearchPart_Result> SearchPart(string sortOrder, string partName)
        {
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            var partNameParameter = partName != null ?
                new ObjectParameter("PartName", partName) :
                new ObjectParameter("PartName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchPart_Result>("SearchPart", sortOrderParameter, partNameParameter);
        }
    
        public virtual ObjectResult<SearchPartDate_Result> SearchPartDate(string sortOrder, string partName, string fromDate, string todate)
        {
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            var partNameParameter = partName != null ?
                new ObjectParameter("PartName", partName) :
                new ObjectParameter("PartName", typeof(string));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var todateParameter = todate != null ?
                new ObjectParameter("Todate", todate) :
                new ObjectParameter("Todate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchPartDate_Result>("SearchPartDate", sortOrderParameter, partNameParameter, fromDateParameter, todateParameter);
        }
    
        public virtual ObjectResult<SearchPartWithBalance_Result> SearchPartWithBalance(string sortOrder, string partName, Nullable<double> baln)
        {
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            var partNameParameter = partName != null ?
                new ObjectParameter("PartName", partName) :
                new ObjectParameter("PartName", typeof(string));
    
            var balnParameter = baln.HasValue ?
                new ObjectParameter("Baln", baln) :
                new ObjectParameter("Baln", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchPartWithBalance_Result>("SearchPartWithBalance", sortOrderParameter, partNameParameter, balnParameter);
        }
    }
}
