//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiniLithoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_billdetails
    {
        public int Sno { get; set; }
        public string Billno { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Copies { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> M_state { get; set; }
        public Nullable<decimal> SCST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public string GSTState { get; set; }
    }
}
