//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiniLithoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_logdetail
    {
        public int Sno { get; set; }
        public string Rno { get; set; }
        public string Rname { get; set; }
        public string Rmobile { get; set; }
        public string Orderdet { get; set; }
        public string paydet { get; set; }
        public string mode { get; set; }
        public string datim { get; set; }
        public string BankRef { get; set; }
    }
}
