//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiniLithoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_officeuse
    {
        public int sno { get; set; }
        public string uname { get; set; }
        public string pword { get; set; }
        public string pin { get; set; }
        public string cname { get; set; }
        public string Phone { get; set; }
        public string emailid { get; set; }
    }
}
