//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiniLithoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_alfserial
    {
        public int SRNO { get; set; }
        public int SERNO { get; set; }
        public string SERALB { get; set; }
    }
}
