//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiniLithoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer
    {
        public int Sno { get; set; }
        public string Cname { get; set; }
        public string address { get; set; }
        public string cphone { get; set; }
        public Nullable<decimal> advance { get; set; }
        public string mode { get; set; }
        public string cdate { get; set; }
    }
}
