//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiniLithoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_expence
    {
        public int sno { get; set; }
        public string Exp_No { get; set; }
        public string Exp_Detail { get; set; }
        public string Exp_Name { get; set; }
        public Nullable<decimal> Exp_Amount { get; set; }
        public Nullable<decimal> Exp_Advance { get; set; }
        public Nullable<System.DateTime> Exp_date { get; set; }
        public Nullable<System.DateTime> CR_date { get; set; }
        public string Exp_Type { get; set; }
    }
}
