//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiniLithoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_newbill
    {
        public string Billno { get; set; }
        public string Name { get; set; }
        public int Sno { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public System.DateTime orderdate { get; set; }
        public System.DateTime deliverydate { get; set; }
        public string rmark { get; set; }
        public string GSTSTAT { get; set; }
        public string M_Status { get; set; }
        public string YLabel { get; set; }
    }
}
